-- 统计分析相关表初始化脚本
USE opendsp;

-- 创建广告统计表
CREATE TABLE IF NOT EXISTS `ad_stat` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    `advertiser_id` INT NOT NULL COMMENT '广告主id',
    `campaign_id` INT NOT NULL COMMENT '推广计划id',
    `ad_group_id` INT NOT NULL COMMENT '广告组id',
    `creative_id` INT NOT NULL COMMENT '创意id',
    `ad_slot_id` INT NOT NULL COMMENT '广告位id',
    `stat_date` DATE NOT NULL COMMENT '统计日期',
    `stat_hour` INT NOT NULL COMMENT '统计小时',
    `requests` BIGINT NOT NULL DEFAULT 0 COMMENT '请求数',
    `bids` BIGINT NOT NULL DEFAULT 0 COMMENT '参与竞价数',
    `wins` BIGINT NOT NULL DEFAULT 0 COMMENT '竞价获胜数',
    `impressions` BIGINT NOT NULL DEFAULT 0 COMMENT '曝光数',
    `clicks` BIGINT NOT NULL DEFAULT 0 COMMENT '点击数',
    `conversions` BIGINT NOT NULL DEFAULT 0 COMMENT '转化数',
    `cost` BIGINT NOT NULL DEFAULT 0 COMMENT '成本/花费（单位：分）',
    `revenue` BIGINT NOT NULL DEFAULT 0 COMMENT '收入（单位：分）',
    `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY `uk_stat_record` (`advertiser_id`, `campaign_id`, `ad_group_id`, `creative_id`, `ad_slot_id`, `stat_date`, `stat_hour`),
    KEY `idx_advertiser_id` (`advertiser_id`),
    KEY `idx_campaign_id` (`campaign_id`),
    KEY `idx_ad_group_id` (`ad_group_id`),
    KEY `idx_creative_id` (`creative_id`),
    KEY `idx_stat_date` (`stat_date`),
    KEY `idx_stat_hour` (`stat_hour`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='广告统计表';

-- 创建创意统计表
CREATE TABLE IF NOT EXISTS `creative_stats` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    `creative_id` INT NOT NULL COMMENT '创意id',
    `advertiser_id` INT NOT NULL COMMENT '广告主id',
    `campaign_id` INT NOT NULL COMMENT '推广计划id',
    `ad_group_id` INT NOT NULL COMMENT '广告组id',
    `ad_slot_id` INT NOT NULL COMMENT '广告位id',
    `stat_date` VARCHAR(10) NOT NULL COMMENT '统计日期，格式yyyyMMdd',
    `stat_hour` INT NOT NULL COMMENT '统计小时',
    `requests` BIGINT NOT NULL DEFAULT 0 COMMENT '请求数',
    `bids` BIGINT NOT NULL DEFAULT 0 COMMENT '参与竞价数',
    `wins` BIGINT NOT NULL DEFAULT 0 COMMENT '竞价获胜数',
    `impressions` BIGINT NOT NULL DEFAULT 0 COMMENT '曝光数',
    `clicks` BIGINT NOT NULL DEFAULT 0 COMMENT '点击数',
    `conversions` BIGINT NOT NULL DEFAULT 0 COMMENT '转化数',
    `cost` BIGINT NOT NULL DEFAULT 0 COMMENT '成本/花费（单位：分）',
    `revenue` BIGINT NOT NULL DEFAULT 0 COMMENT '收入（单位：分）',
    `ctr` DECIMAL(10,6) NOT NULL DEFAULT 0 COMMENT '点击率（clicks/impressions）',
    `cpm` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '千次展示成本',
    `cpc` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '每次点击成本',
    `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
    `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
    UNIQUE KEY `uk_creative_stats` (`creative_id`, `stat_date`, `stat_hour`),
    KEY `idx_creative_id` (`creative_id`),
    KEY `idx_advertiser_id` (`advertiser_id`),
    KEY `idx_campaign_id` (`campaign_id`),
    KEY `idx_ad_group_id` (`ad_group_id`),
    KEY `idx_stat_date` (`stat_date`),
    KEY `idx_stat_hour` (`stat_hour`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='创意统计表';

-- 创建竞价日志表
CREATE TABLE IF NOT EXISTS `bid_log` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    `request_id` VARCHAR(64) NOT NULL COMMENT '竞价请求ID',
    `advertiser_id` INT NOT NULL COMMENT '广告主id',
    `campaign_id` INT NOT NULL COMMENT '推广计划id',
    `ad_group_id` INT NOT NULL COMMENT '广告组id',
    `creative_id` INT NOT NULL COMMENT '创意id',
    `ad_slot_id` INT COMMENT '广告位id',
    `adx_id` VARCHAR(50) NOT NULL COMMENT 'ADX平台标识',
    `adx_slot_id` VARCHAR(100) COMMENT 'ADX广告位ID',
    `bid_price` BIGINT NOT NULL COMMENT '出价（单位：分）',
    `win_price` BIGINT COMMENT '成交价（单位：分）',
    `is_win` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否中标：0-未中标,1-中标',
    `user_id` VARCHAR(100) COMMENT '用户ID',
    `device_id` VARCHAR(100) COMMENT '设备ID',
    `ip` VARCHAR(45) COMMENT '用户IP',
    `user_agent` VARCHAR(500) COMMENT '用户代理',
    `geo_country` VARCHAR(50) COMMENT '国家',
    `geo_region` VARCHAR(50) COMMENT '地区',
    `geo_city` VARCHAR(50) COMMENT '城市',
    `device_type` VARCHAR(50) COMMENT '设备类型',
    `os` VARCHAR(50) COMMENT '操作系统',
    `browser` VARCHAR(50) COMMENT '浏览器',
    `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    KEY `idx_request_id` (`request_id`),
    KEY `idx_advertiser_id` (`advertiser_id`),
    KEY `idx_campaign_id` (`campaign_id`),
    KEY `idx_ad_group_id` (`ad_group_id`),
    KEY `idx_creative_id` (`creative_id`),
    KEY `idx_adx_id` (`adx_id`),
    KEY `idx_is_win` (`is_win`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='竞价日志表';

-- 创建曝光日志表
CREATE TABLE IF NOT EXISTS `impression_log` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    `request_id` VARCHAR(64) NOT NULL COMMENT '竞价请求ID',
    `advertiser_id` INT NOT NULL COMMENT '广告主id',
    `campaign_id` INT NOT NULL COMMENT '推广计划id',
    `ad_group_id` INT NOT NULL COMMENT '广告组id',
    `creative_id` INT NOT NULL COMMENT '创意id',
    `ad_slot_id` INT COMMENT '广告位id',
    `adx_id` VARCHAR(50) NOT NULL COMMENT 'ADX平台标识',
    `adx_slot_id` VARCHAR(100) COMMENT 'ADX广告位ID',
    `win_price` BIGINT NOT NULL COMMENT '成交价（单位：分）',
    `user_id` VARCHAR(100) COMMENT '用户ID',
    `device_id` VARCHAR(100) COMMENT '设备ID',
    `ip` VARCHAR(45) COMMENT '用户IP',
    `user_agent` VARCHAR(500) COMMENT '用户代理',
    `geo_country` VARCHAR(50) COMMENT '国家',
    `geo_region` VARCHAR(50) COMMENT '地区',
    `geo_city` VARCHAR(50) COMMENT '城市',
    `device_type` VARCHAR(50) COMMENT '设备类型',
    `os` VARCHAR(50) COMMENT '操作系统',
    `browser` VARCHAR(50) COMMENT '浏览器',
    `is_settled` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已结算：0-未结算,1-已结算',
    `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    KEY `idx_request_id` (`request_id`),
    KEY `idx_advertiser_id` (`advertiser_id`),
    KEY `idx_campaign_id` (`campaign_id`),
    KEY `idx_ad_group_id` (`ad_group_id`),
    KEY `idx_creative_id` (`creative_id`),
    KEY `idx_adx_id` (`adx_id`),
    KEY `idx_is_settled` (`is_settled`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='曝光日志表';

-- 创建点击日志表
CREATE TABLE IF NOT EXISTS `click_log` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    `request_id` VARCHAR(64) NOT NULL COMMENT '竞价请求ID',
    `advertiser_id` INT NOT NULL COMMENT '广告主id',
    `campaign_id` INT NOT NULL COMMENT '推广计划id',
    `ad_group_id` INT NOT NULL COMMENT '广告组id',
    `creative_id` INT NOT NULL COMMENT '创意id',
    `ad_slot_id` INT COMMENT '广告位id',
    `adx_id` VARCHAR(50) NOT NULL COMMENT 'ADX平台标识',
    `adx_slot_id` VARCHAR(100) COMMENT 'ADX广告位ID',
    `click_price` BIGINT NOT NULL COMMENT '点击价格（单位：分）',
    `user_id` VARCHAR(100) COMMENT '用户ID',
    `device_id` VARCHAR(100) COMMENT '设备ID',
    `ip` VARCHAR(45) COMMENT '用户IP',
    `user_agent` VARCHAR(500) COMMENT '用户代理',
    `geo_country` VARCHAR(50) COMMENT '国家',
    `geo_region` VARCHAR(50) COMMENT '地区',
    `geo_city` VARCHAR(50) COMMENT '城市',
    `device_type` VARCHAR(50) COMMENT '设备类型',
    `os` VARCHAR(50) COMMENT '操作系统',
    `browser` VARCHAR(50) COMMENT '浏览器',
    `is_valid` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否有效点击：0-无效,1-有效',
    `is_settled` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已结算：0-未结算,1-已结算',
    `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    KEY `idx_request_id` (`request_id`),
    KEY `idx_advertiser_id` (`advertiser_id`),
    KEY `idx_campaign_id` (`campaign_id`),
    KEY `idx_ad_group_id` (`ad_group_id`),
    KEY `idx_creative_id` (`creative_id`),
    KEY `idx_adx_id` (`adx_id`),
    KEY `idx_is_valid` (`is_valid`),
    KEY `idx_is_settled` (`is_settled`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='点击日志表';

-- 创建转化日志表
CREATE TABLE IF NOT EXISTS `conversion_log` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    `request_id` VARCHAR(64) NOT NULL COMMENT '竞价请求ID',
    `advertiser_id` INT NOT NULL COMMENT '广告主id',
    `campaign_id` INT NOT NULL COMMENT '推广计划id',
    `ad_group_id` INT NOT NULL COMMENT '广告组id',
    `creative_id` INT NOT NULL COMMENT '创意id',
    `ad_slot_id` INT COMMENT '广告位id',
    `adx_id` VARCHAR(50) NOT NULL COMMENT 'ADX平台标识',
    `conversion_type` INT NOT NULL COMMENT '转化类型：1-下载,2-注册,3-购买,4-其他',
    `conversion_value` BIGINT NOT NULL DEFAULT 0 COMMENT '转化价值（单位：分）',
    `user_id` VARCHAR(100) COMMENT '用户ID',
    `device_id` VARCHAR(100) COMMENT '设备ID',
    `ip` VARCHAR(45) COMMENT '用户IP',
    `is_valid` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否有效转化：0-无效,1-有效',
    `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    KEY `idx_request_id` (`request_id`),
    KEY `idx_advertiser_id` (`advertiser_id`),
    KEY `idx_campaign_id` (`campaign_id`),
    KEY `idx_ad_group_id` (`ad_group_id`),
    KEY `idx_creative_id` (`creative_id`),
    KEY `idx_conversion_type` (`conversion_type`),
    KEY `idx_is_valid` (`is_valid`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='转化日志表';

-- 创建财务结算表
CREATE TABLE IF NOT EXISTS `financial_settlement` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    `advertiser_id` INT NOT NULL COMMENT '广告主id',
    `settlement_date` DATE NOT NULL COMMENT '结算日期',
    `impressions` BIGINT NOT NULL DEFAULT 0 COMMENT '曝光数',
    `clicks` BIGINT NOT NULL DEFAULT 0 COMMENT '点击数',
    `conversions` BIGINT NOT NULL DEFAULT 0 COMMENT '转化数',
    `total_cost` BIGINT NOT NULL DEFAULT 0 COMMENT '总成本（单位：分）',
    `balance_before` BIGINT NOT NULL DEFAULT 0 COMMENT '结算前余额（单位：分）',
    `balance_after` BIGINT NOT NULL DEFAULT 0 COMMENT '结算后余额（单位：分）',
    `settlement_status` INT NOT NULL DEFAULT 0 COMMENT '结算状态：0-待结算,1-已结算',
    `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY `uk_advertiser_settlement` (`advertiser_id`, `settlement_date`),
    KEY `idx_advertiser_id` (`advertiser_id`),
    KEY `idx_settlement_date` (`settlement_date`),
    KEY `idx_settlement_status` (`settlement_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='财务结算表'; 